  import 'package:flutter/material.dart';

   // padding, margin
   const double padding0 = 0;
   const double padding1 = 1;
   const double padding3 = 3;
   const double padding2 = 2;
   const double padding4 = 4;
   const double padding5 = 5;
   const double padding6 = 6;
   const double padding7 = 7;
   const double padding8 = 8;
   const double padding9 = 9;
   const double padding10 = 10;
   const double padding12 = 12;
   const double padding13 = 13;
   const double padding14 = 14;
   const double padding15 = 15;
   const double padding16 = 16;
   const double padding17 = 17;
   const double padding18 = 18;
   const double padding19 = 19;
   const double padding20 = 20;
   const double padding21 = 21;
   const double padding22 = 22;
   const double padding23 = 23;
   const double padding24 = 24;
   const double padding25 = 25;
   const double padding26 = 26;
   const double padding28 = 28;
   const double padding29 = 29;
   const double padding30 = 30;
   const double padding31 = 31;
   const double padding32 = 32;
   const double padding33 = 33;
   const double padding34 = 34;
   const double padding35 = 35;
   const double padding40 = 40;
   const double padding45 = 45;
   const double padding50 = 50;
   const double padding55 = 55;
   const double padding56 = 56;
   const double padding60 = 60;
   const double padding65 = 65;
   const double padding70 = 70;
   const double padding80 = 80;
   const double padding85 = 85;
   const double padding90 = 90;
   const double padding100 = 100;

   const double largeText = 19;
   const double labelText = 17;
   const double hintText = 15;
   const double smallText = 14;
   const double mediumText = 16;
   const double normalText = 15;
   const double extraMediumText = 17;
   const double extraSmall = 12;

   const EdgeInsets primaryPadding = EdgeInsets.only(
      left: padding16, right: padding16);